version: 2.1

executors:
  node_16:
    docker:
      - image: circleci/node:16
  ubuntu:
    machine:
      image: ubuntu-2204:2022.07.1
    resource_class: arm.large

commands:
  # debug only
  halt:
    steps:
      - run: circleci step halt

  # https://circleci.com/docs/2.0/caching/#basic-example-of-dependency-caching
  save_dependencies:
    steps:
      - save_cache:
          key: yarn-deps-v1-{{ checksum "./yarn.lock" }}
          paths:
            - ./node_modules

  # https://circleci.com/docs/2.0/caching/#restoring-cache
  load_dependencies:
    steps:
      - restore_cache:
          keys:
            - yarn-deps-v1-{{ checksum "./yarn.lock" }}

  shape_ubuntu:
    steps:
      - run:
          name: Install Yarn lib
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash
            echo 'export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"' >> $BASH_ENV
          no_output_timeout: 120s

  setup:
    steps:
      - shape_ubuntu
      - checkout
      - load_dependencies
      - run:
          name: Set .evn.yml file from CI "ENV_FILE" (base64 env variable)
          command: echo "$ENV_FILE" | base64 --decode > ./config/.env.yml
      - run:
          command: yarn install
          no_output_timeout: 180s
      - save_dependencies

  run_tests:
    steps:
      - run:
          command: yarn lint
          no_output_timeout: 120s
      - run:
          command: yarn lint:tsc
          no_output_timeout: 120s
      - run:
          name: Test changed files only
          command: yarn test:ci --passWithNoTests --coverage=false $((git diff --name-only --diff-filter=ACMR origin/main.. | grep -i -E '\.([jt]sx?)$' | grep -v -i '.stories.') || echo 'no-files')
          no_output_timeout: 180s

  run_publicate_staging:
    steps:
      - run:
          name: Build staging with Sentry
          command: yarn build --env SENTRY-staging
          no_output_timeout: 180s
      - run:
          name: Deploy staging files
          command: yarn deploy staging
          no_output_timeout: 120s

  run_publicate_production:
    steps:
      - run:
          name: Build production with Sentry
          command: yarn build --env SENTRY-production
          no_output_timeout: 180s
      - run:
          name: Deploy production files
          command: yarn deploy production
          no_output_timeout: 120s

jobs:
  'Tests and Coverage':
    executor: ubuntu
    steps:
      - setup
      - run_tests
  'Canary build':
    executor: ubuntu
    steps:
      - setup
      - run_tests
      - run_publicate_staging
  'Production build':
    executor: ubuntu
    steps:
      - setup
      - run_tests
      - run_publicate_production

workflows:
  pr-tests:
    jobs:
      - 'Tests and Coverage':
          context: custom-context
          filters:
            branches:
              ignore:
                - main

  merge-build:
    jobs:
      - 'Production build':
          context: custom-context
          filters:
            branches:
              only:
                - main
