#!/bin/sh

if [ -t 1 ]; then
  exec < /dev/tty
fi

cd "$(git rev-parse --show-toplevel)"

STAGED_FILES=($(git diff --cached --name-only --diff-filter=ACMR))
STAGED_FILES_PRETTIER=($(git diff --cached --name-only --diff-filter=ACMR | grep -i -E '\.(yml|s?css|json|[jt]sx?)$'))
STAGED_FILES_ESLINT=($(git diff --cached --name-only --diff-filter=ACMR | grep -i -E '\.([jt]sx?)$'))
STAGED_FILES_JEST=($(git diff --cached --name-only --diff-filter=ACMR | grep -i -E '\.([jt]sx?)$' | grep -v -i '.stories.'))

set -be

echo "Prettier: ${#STAGED_FILES_PRETTIER[@]} file(s)."
if [[ "$STAGED_FILES_PRETTIER" = "" ]]; then
  echo "    Prettier not required"
else
  yarn prettier "${STAGED_FILES_PRETTIER[@]}" --write
fi

echo "ESLint: ${#STAGED_FILES_ESLINT[@]} file(s)"
if [[ "$STAGED_FILES_ESLINT" = "" ]]; then
  echo "    ESLint not required"
else
  yarn lint "${STAGED_FILES_ESLINT[@]}" --fix
fi

# Re-add files since they may have been fixed
git add "${STAGED_FILES[@]}"

yarn lint:tsc

exit 0
